### ISSUE TITLE
PPT store to s3 and return download URL

### ISSUE THREAD

**Issue by hafen** [pcstout/sls_ki_synapse#12]
Instead of storing the generated PPT on Synapse, put it on s3 and return the URL. I think it's fine for the PPT to go to a "public" s3 bucket but I think we can set an expiration date on the file, something like 1 minute since it will be downloaded right away.

**Comment by hafen** [comment]
@jonathan-cognition

**Comment by pcstout** [comment]
This change is in progress here: https://github.com/pcstout/sls_ki_synapse/pull/16
